import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../context/AuthContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { ContactProvider } from "../context/ContactContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<AuthProvider>
					<ContactProvider>
						<ToastContainer
							position="top-center"
							draggable={false}
							hideProgressBar
							limit={3}
							pauseOnHover={true}
							pauseOnFocusLoss={false}
						/>
						<div className="flex min-h-screen flex-col items-center justify-between p-8">
							<main className="container mx-auto px-4 py-8">{children}</main>
						</div>
					</ContactProvider>
				</AuthProvider>
			</body>
		</html>
	);
}
